---
title: "p8105_hw5_rl3616"
author: "Ruipeng Li"
date: "`r format(Sys.Date())`"
output: github_document
---

```{r}
library(tidyverse)
set.seed(123)
```

### Problem 1

```{r}
has_duplicate_birthday <- function(n) {
  b <- sample(1:365, size = n, replace = TRUE)
  any(duplicated(b))
  }
group_size = 2:50
n_sim = 10000

birthday_results <- map_df(
  group_size,
  ~ tibble(
    n = .x, 
    dup = replicate(n_sim, has_duplicate_birthday(.x))
    )
  )

prob_by_n <- birthday_results |>
  group_by(n) |> 
  summarise(prob_dup = mean(dup), .groups = "drop")

prob_by_n
```

```{r}
ggplot(prob_by_n, aes(x = n, y = prob_dup)) +
  geom_line() +
  geom_point() +
  labs(
    x = "Group size (n)",
    y = "P(at least two share a birthday)",
    title = "Birthday Duplicate Simulation"
    ) +
  theme_minimal()
```  
As shown in the plot, when the group size is very small, the probability of having a shared birthday is close to zero. As the group size increases, the probability rises rapidly. Around a group size of 25, the rate of increase begins to slow down, and eventually the probability approaches 100%.

### Problem 2

```{r}
n <- 30
sigma <- 5
n_sim <- 5000
mu_vec <- 0:6

sim_one_mu <- function(mu, n = 30, sigma = 5, n_sim = 5000) {
  
  map(1:n_sim, ~{
    x <- rnorm(n, mean = mu, sd = sigma)
    
    t_tidy <- broom::tidy(t.test(x, mu = 0))
    
    tibble(
      mu_true = mu,
      mu_hat = t_tidy$estimate,
      p_value = t_tidy$p.value
    )
  }) |> 
    list_rbind()
}

mu_sim_results <- map_df(mu_vec, sim_one_mu)

mu_sim_results
```

#### proportion of times the null was rejected

```{r}
power_by_mu <- mu_sim_results |>
  group_by(mu_true) |>
  summarise(
    power = mean(p_value < 0.05),
    .groups = "drop"
  )

power_by_mu

rej_prop_plot <- power_by_mu |> 
  ggplot(aes(x = mu_true, y = power)) +
  geom_line() +
  geom_point() +
  labs(
    x = "True mean μ",
    y = "Proportion of reject H0",
    title = "Power of one-sample t-test vs effect size"
  )

rej_prop_plot
  
```


#### mu estimate plot

```{r}
mu_hat_avg <- mu_sim_results |> 
  group_by(mu_true) |> 
  summarise(
    mean_mu_hat_avg = mean(mu_hat),
    .groups = "drop"
  )

mu_hat_rej <- mu_sim_results |> 
  filter(p_value < 0.5) |> 
  group_by(mu_true) |> 
  summarise(
    mean_mu_hat_rej = mean(mu_hat),
    .groups = "drop"
  )

mu_estimate_plot <- mu_hat_avg |> 
  left_join(mu_hat_rej, by = "mu_true") |> 
  ggplot(aes(x = mu_true)) +
    geom_line(aes(y = mean_mu_hat_avg, color = "All samples")) +
    geom_point(aes(y = mean_mu_hat_avg, color = "All samples")) +
    geom_line(aes(y = mean_mu_hat_rej, color = "Only significant (p < 0.05)")) +
    geom_point(aes(y = mean_mu_hat_rej, color = "Only significant (p < 0.05)")) +
    geom_abline(slope = 1, intercept = 0, linetype = "dashed") +
    labs(
      x = "True mean μ",
      y = "Average of μ̂",
      color = "",
      title = "Average estimate vs true μ"
    )

mu_estimate_plot
```